### ISSUE TITLE
Unable to use serial ports

### ISSUE THREAD

**Issue by PatW-sys** [snapcrafters/arduino#14]
Hi, I need a little help. 
I tried a whole bunch of possibilities to fix my issue but nothing worked. 
When starting the IDE with/without attached Arduino (nano MEGA 328P) on my Ubuntu 20.04.1 it is related to /dev/ttyS0. 
And I'm not able to fix this issue. I already tried to do the commands on Issue #10  but it didn't worked. 
I also tried to use the IDE 1.8.13 and the unstable 1.9.0-beta. 

In the /dev/ folder there is also the ttyACM0 or ttyUSB0 missing. 

So far I spend several hours on trying to fix this issue but I can't.  

Has had anyone this problem and a solution? 

Best regards 
Pat

**Comment by merlijn-sebrechts** [comment]
This repository only tracks issues specific to the snap. If you're having the same issues with the version installed from arduino itself, then it's not an issue with the snap.

The people on the [Arduino Forum](https://forum.arduino.cc/) might be able to help you further.

Feel free to re-open if you can only reproduce this issue with the snap version of arduino.
