### ISSUE TITLE
Cany use ports on Arduino IDE

### ISSUE THREAD

**Issue by regus245** [snapcrafters/arduino#15]
Hi 
Could someone help me, I have installed the Arduino IDE on my laptop running Linux Ubuntu, I got a message  when I opened the IDE  station that I would not be able to load any boards as I will not have permissions to use the USB ports? 
I was told to run the following line in terminal " sudo usermod -a -G dialout <username>
When I run this line I get an error message saying that "dialout" does not exist.
dose anyone have a work round for this issue.

Many thanks

Regus

**Comment by merlijn-sebrechts** [comment]
Hi Regus. Could copy and paste the exact error message here? Thanks!

**Comment by merlijn-sebrechts** [comment]
Please reopen your issue if you can provide the exact info.
