### ISSUE TITLE
Install plugin ESP8266FS

### ISSUE THREAD

**Issue by FilipDem** [snapcrafters/arduino#19]
Hi, 
I want to install the plugin ESP8266FS, however I am facing the "read-only" problem of the snap directory.
Is there any workaround?
Kr,

**Comment by merlijn-sebrechts** [comment]
Hi

Can you explain or link to the steps you take to install the plugin? Normally you should be able to install any package using the board manager and the library manager inside the IDE itself.

**Comment by FilipDem** [comment]
Sorry having annoyed you, we can close the topic... 
I tried to install the plugin in /snap/.../tools while it should be in ~/snap.../tools.
