### ISSUE TITLE
No permission to load projects from locations other than home directory

### ISSUE THREAD

**Issue by Bruzzlee** [snapcrafters/arduino#3]
A file located other than somewhere in the home directory can't be accessed.

Example error:
Error opening directory '/media/xyz': Permission denied

Might by solved if "removable-media" will be added as a plug to this snap.

**Comment by Bruzzlee** [comment]
Fixed in commit https://github.com/snapcrafters/arduino/commit/ec471a4b66c481558d294dd59ad54821808a7722

**Comment by merlijn-sebrechts** [comment]
Thanks, I forgot to follow-up. This is now in the stable channel.
