### ISSUE TITLE
Unable to upload sketch Over The Air (ESP boards)

### ISSUE THREAD

**Issue by guneemwelloeux** [snapcrafters/arduino#6]
Following the conversation about OTA sketch upload in a previous issue, I can confirm that the snap is not allowing any upload to a network port.
In the case of the ESP32 and the ESP8266, the upload fails with the following error:
```
09:21:45 [ERROR]: Listen Failed
```
After having a look at the script doing the upload, and modifying the `except` block to show the undelying error, I can see that the error is caused by a missing permission when the script is calling `socket.bind`.

Based on this, I reckon the snap in missing the `network-bind` plug.

**Comment by merlijn-sebrechts** [comment]
Thanks for checking this out! 

The latest version in stable has the `network-bind` plug. Can you try again?

**Comment by guneemwelloeux** [comment]
OTA updates work perfectly with the latest stable version!
Thanks!

**Comment by merlijn-sebrechts** [comment]
Thank you!
